### ISSUE TITLE
Running ActiveNeuralSLAM on Matterport3D

### ISSUE THREAD

**Issue by LaughBuddha** [devendrachaplot/Neural-SLAM#32]
Hi,

I am able to run Neural-SLAM successfully on gibson. But, I'm not able to get it run on Matterport3D. I've followed the steps in #16 and done the setup in the exact same manner. I'm getting a different error as follows.

```
(ActiveNeuralSLAM) sidgoel@node-1080ti-0:~/Neural-SLAM$ python  main.py --split val_mt_small --eval 1 --auto_gpu_config 0 -n 1 --num_episodes 1 --num_processes_per_gpu 10 --load_global pretrained_models/model_best.global --train_global 0 --load_local pretrained_models/model_best.local  --train_local 0 --load_slam pretrained_models/model_best.slam  --train_slam 0 --total_num_scenes 1 --task_config "tasks/pointnav_mp3d.yaml"
Dumping at ./tmp//models/exp1/
Namespace(alpha=0.99, auto_gpu_config=0, camera_height=1.25, clip_param=0.2, collision_threshold=0.2, cuda=True, du_scale=2, dump_location='./tmp/', entropy_coef=0.001, env_frame_height=256, env_frame_width=256, eps=1e-05, eval=1, exp_loss_coeff=1.0, exp_name='exp1', frame_height=128, frame_width=128, gamma=0.99, global_downscaling=2, global_hidden_size=256, global_lr=2.5e-05, goals_size=2, hfov=90.0, load_global='pretrained_models/model_best.global', load_local='pretrained_models/model_best.local', load_slam='pretrained_models/model_best.slam', local_hidden_size=512, local_optimizer='adam,lr=0.0001', local_policy_update_freq=5, log_interval=10, map_pred_threshold=0.5, map_resolution=5, map_size_cm=2400, max_episode_length=1000, max_grad_norm=0.5, no_cuda=False, noise_level=1.0, noisy_actions=1, noisy_odometry=1, num_episodes=1, num_global_steps=40, num_local_steps=25, num_mini_batch=0, num_processes=1, num_processes_on_first_gpu=0, num_processes_per_gpu=10, obs_threshold=1, obstacle_boundary=5, pose_loss_coeff=10000.0, ppo_epoch=4, pretrained_resnet=1, print_images=0, proj_loss_coeff=1.0, randomize_env_every=1000, save_interval=1, save_periodic=500000, save_trajectory_data='0', seed=1, short_goal_dist=1, sim_gpu_id=0, slam_batch_size=72, slam_iterations=10, slam_memory_size=500000, slam_optimizer='adam,lr=0.0001', split='val_mt_small', task_config='tasks/pointnav_mp3d.yaml', tau=0.95, total_num_scenes='1', train_global=0, train_local=0, train_slam=0, use_deterministic_local=0, use_gae=False, use_pose_estimation=2, use_recurrent_global=0, use_recurrent_local=1, value_loss_coef=0.5, vis_type=1, vision_range=64, visualize=0)
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/beegfs/home/sidgoel/Neural-SLAM/env/habitat/habitat_api/habitat/core/vector_env.py", line 148, in _worker_env
    env = env_fn(*env_fn_args)
  File "/mnt/beegfs/home/sidgoel/Neural-SLAM/env/habitat/__init__.py", line 17, in make_env_fn
    config_env.SIMULATOR.SCENE = dataset.episodes[0].scene_id
IndexError: list index out of range
```

Also, I ran the `examples/example.py` for `habitat-sim` with `mp3d` and it works fine.
![image](https://user-images.githubusercontent.com/18654826/108613596-9653a280-7419-11eb-9b80-4ec0d94f0890.png)

Request help with the same.

**Comment by LaughBuddha** [comment]
Resolved  by converting the matterport3D dataset to multiple thread format using the following 
`python scripts/convert_datasets.py`
