### ISSUE TITLE
ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.

### ISSUE THREAD

**Issue by CwwwwS** [devendrachaplot/Neural-SLAM#39]
when I used this  command   `python main.py -n1 --auto_gpu_config 0 --split val` 

I got 

2021-06-04 21:17:23,075 initializing task Nav-v0
2021-06-04 21:17:23,083 Computing map for data/scene_datasets/gibson/Cantwell.glb
num:0
Time: 00d 00h 00m 00s, num timesteps 0, FPS 0,
        Rewards:
        Losses:
Time: 00d 00h 00m 01s, num timesteps 10, FPS 7,
        Rewards:
        Losses: Local Loss: 0.000,
/opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL 
file=/opt/conda/condabld/pytorch_1565272279342/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu line=110 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "main.py", line 797, in <module>
    main()
  File "main.py", line 372, in main
    tmp = loss(action_prob, action_target)
  File "/home/ad-yang/miniconda3/envs/Neural-SLAM/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ad-yang/miniconda3/envs/Neural-SLAM/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/ad-yang/miniconda3/envs/Neural-SLAM/lib/python3.6/site-packages/torch/nn/functional.py", line 1995, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/ad-yang/miniconda3/envs/Neural-SLAM/lib/python3.6/site-packages/torch/nn/functional.py", line 1824, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:110

I don't know how to solve this problem.
Hope to get your reply.

**Comment by devendrachaplot** [comment]
This seems to be an issue with your CUDA or pytorch installation and does not seem to be related to the Neural-SLAM code.
