### ISSUE TITLE
ninja error

### ISSUE THREAD

**Issue by Leeable** [devendrachaplot/Neural-SLAM#40]
git clone https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim; git checkout 9575dcd45fe6f55d2a44043833af08972a7895a9; 
pip install -r requirements.txt; 
python setup.py install --headless

when i did last one, it shows:

ninja: error: loading 'build.ninja': No such file or directory
Traceback (most recent call last):
  File "setup.py", line 361, in <module>
    zip_safe=False,
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 195, in run
    self.build_extension(ext)
  File "setup.py", line 256, in build_extension
    shlex.split("cmake --build {}".format(self.build_temp)) + build_args
  File "/home/liqunzhao/anaconda3/envs/neuslam/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'build', '--config', 'RelWithDebInfo', '--']' returned non-zero exit status 1.

**Comment by devendrachaplot** [comment]
Unfortunately, I can not help much with habitat installation. You could try opening an issue on the Habitat github repository or join and ask on the public habitat slack channel.
