### ISSUE TITLE
ModuleNotFoundError: No module named 'habitat'

### ISSUE THREAD

**Issue by rushibs** [devendrachaplot/Neural-SLAM#64]
I followed all the steps mentioned to reproduce the codebase. However, I am getting the error shown below when I run the following command: 

python3 main.py -n1 --auto_gpu_config 0 --split val

ERROR:

 Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from env import make_vec_envs
  File "/home/USER/Neural-SLAM/env/__init__.py", line 3, in <module>
    from .habitat import construct_envs
  File "/home/USER/Neural-SLAM/env/habitat/__init__.py", line 6, in <module>
    from habitat.config.default import get_config as cfg_env
ModuleNotFoundError: No module named 'habitat'

Could you kindly guide me what the issue could be and how to resolve it?

**Comment by snowBrain** [comment]
u can change “ import env.habitat.utils.pose as pu” to “from env.habitat.utils import pose as pu” and “import env.habitat.utils.visualizations as vu” to "from env.habitat.utils import visualizations as vu"

**Comment by sahusiddharth** [comment]
Hi @rushibs, were you able to resolve it?

Hi @snowBrain, I tried what you suggested but the error is still there, can you please help me resolve it?
